name: on-github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
     # Every hour between 8 pm and 7 am PST on weekday
    - cron:  '0 3-14 * * 1-5' # https://crontab.guru/#0_3-14_*_*_1-5

jobs:
  build-and-test:

    runs-on: macos-latest
    timeout-minutes: 20
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Change Local name to avoid name clash causing alert
      run: |
        sudo scutil --set LocalHostName "SpartaConnectGitHubCI"
        sudo scutil --set ComputerName "SpartaConnectGitHubCI"
    - name: Do not disturb the build with Notifications
      run: |
        npm install --global do-not-disturb-cli
        do-not-disturb on
    - name: Disable firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
#   Breaks clicking on menu bar button
#    - name: Close Finder windows not to obscure test screenshots
#      run: launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
    - name: Close Finder Windows using Apple Script
      run: sudo osascript -e 'tell application "Finder" to close windows'
    - name: Close Notification window
      run: killall UserNotificationCenter || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2.3.1
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: bundled-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: Testable
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: SpartaConnect
        action: build
    - name: App Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: AppSpecs
    - name: UI Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: UITests
        build-settings: -resultBundlePath ui-tests -test-timeouts-enabled YES
    - name: Sparta Metrics
      env:
        SUBMIT_METRICS_URL: ${{ secrets.SUBMIT_METRICS_URL }}
      run: ./bin/post-sparta-metrics.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp /tmp/rare-test-events.plist . || true
        zip -r results.zip ui-tests.xcresult || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rare-test-events.plist
        path: rare-test-events.plist
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      if: always()  # Setup credentials even if the workflow failed
    - name: Log Build
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()  # Need to run to log the workflow failure
