name: on-github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Disable firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
#   Breaks clicking on menu bar button
#    - name: Close Finder windows not to obscure test screenshots
#      run: launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
    - name: Close Finder Windows using Apple Script
      run: |
        sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.finder')" || true
        osascript -e 'tell application "Finder" to close windows'
    - name: Close Notification window
      run: killall UserNotificationCenter || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2.3.1
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: Testable
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: SpartaConnect
        action: build
    - name: App Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: AppSpecs
    - name: UI Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: UITests
        build-settings: -resultBundlePath ui-tests
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
