name: on-github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Disable firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
    - name: Close Finder
      run: launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
    - name: Close Notification window
      run: killall UserNotificationCenter || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2
    - name: Unit Specs
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme Testable test | xcpretty
    - name: Build
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme App build | xcpretty
    - name: App Specs
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme AppSpecs test | xcpretty
    - name: UI Tests
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme UITests test -resultBundlePath ui-tests | xcpretty
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
