name: deflaking-on-self-hosted

on:
  push:
    branches:
      - master            # detect flakiness
      - deflake-ui-tests  # debug this workflow
  schedule:
    # Every 30 min on weekday nights (between 8 pm and 7 am PST)
    - cron:  '*/30 3-14 * * 1-5' # https://crontab.guru/#*/30_3-14_*_*_1-5
    # Every 30 min on weekend
    - cron:  '*/30 * * * 0,6'  # https://crontab.guru/#*/30_*_*_*_0,6

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-then-test:

    runs-on: self-hosted
    timeout-minutes: 45

    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES

    steps:
    - name: Cancel when screen is locked
      uses: sparta-science/cancel-on-screen-lock@v0.2
      with:
        repo-token: ${{ github.token }}
    - run: rm ~/Library/Keychains/certs.keychain-db || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: bundle
      run: |
        ruby -v
        gem install bundler:2.1.4 --conservative
        bundle
    - name: deflake UI Tests
      env:
        SUBMIT_METRICS_URL: ${{ secrets.SUBMIT_METRICS_URL }}
        TIME_LIMIT_MINUTES: 25
      run: |
        bin/dev/deflake-ui-tests.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp /tmp/events-detected-during-ui-tests.txt . || true
        zip -r results.zip test-results/ui-tests-latest.xcresult || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: events-detected-during-ui-tests.txt
        path: events-detected-during-ui-tests.txt
        if-no-files-found: ignore
