name: self-hosted-test

on:
  push:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-then-test:

    runs-on: self-hosted
    timeout-minutes: 20

    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES

    steps:
    - name: Cancel when screen is locked
      uses: sparta-science/cancel-on-screen-lock@v0.2
      with:
        repo-token: ${{ github.token }}
    - run: rm ~/Library/Keychains/certs.keychain-db || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: bundle
      run: |
        ruby -v
        gem install bundler:2.1.4 --conservative
        bundle
    - name: Unit Specs
      run: ./bin/xc-scheme.sh Testable clean test
    - name: Code Coverage for Framework
      run: bash <(curl -s https://codecov.io/bash) -J '^Testable$' -F unit-specs
    - name: Build
      run: ./bin/xc-scheme.sh SpartaConnect clean build
    - name: App Specs
      run: ./bin/xc-scheme.sh AppSpecs test
#    - name: codecov/codecov-action@v1.0.7
#      with:
#        flags: AppSpecs
#        name: self-hosted
#
    - name: Code Coverage for App target
      run: bash <(curl -s https://codecov.io/bash) -J '^SpartaConnect$' -F app-specs
    - name: UI Tests
      run: ./bin/xc-scheme.sh UITests test -resultBundlePath ui-tests
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      if: always()  # Setup credentials even if the workflow failed
    - name: Log Build
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()  # Need to run to log the workflow failure
    - name: Sparta Metrics
      env:
        SUBMIT_METRICS_URL: ${{ secrets.SUBMIT_METRICS_URL }}
      run: ./bin/post-sparta-metrics.sh
    - name: AWS Event Metrics
      run: |
        brew outdated awscli || brew install awscli
        ./bin/post-aws-metrics.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp /tmp/rare-test-events.plist . || true
        zip -r results.zip ui-tests.xcresult || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rare-test-events.plist
        path: rare-test-events.plist
