name: self-hosted-test

on:
  push:
  schedule: # Every 10 min between 8 pm and 7 am PST
    - cron:  '*/10 3-14 * * *' # https://crontab.guru/#*/10_3-14_*_*_*

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-then-test:

    runs-on: self-hosted
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES

    steps:
    - run: rm ~/Library/Keychains/certs.keychain-db || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Ruby version
      run: echo $(ruby -v)
    - name: bundle
      run: |
        gem install bundler
        bundle
    - name: Unit Specs
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme Testable clean test | xcpretty
    - name: Code Coverage for Framework
      run: bash <(curl -s https://codecov.io/bash) -J 'Testable'
    - name: Build
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme SpartaConnect clean build | xcpretty
    - name: App Specs
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme AppSpecs test | xcpretty
#    - name: codecov/codecov-action@v1.0.7
#      with:
#        flags: AppSpecs
#        name: self-hosted
#
    - name: Code Coverage for App target
      run: bash <(curl -s https://codecov.io/bash) -J '^SpartaConnect$'
    - name: UI Tests
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme UITests test -resultBundlePath ui-tests | xcpretty
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
