name: self-hosted-test

on:
  push:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-then-test:

    runs-on: self-hosted
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES

    steps:
    - run: rm ~/Library/Keychains/certs.keychain-db || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: bundle
      run: |
        ruby -v
        gem install bundler:2.1.4 --conservative
        bundle
    - name: UI Tests
      run: ./bin/xc-scheme.sh UITests test -resultBundlePath ui-tests
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
      if: always()  # Setup credentials even if the workflow failed
    - name: Log Build
      # replace TAG by the latest tag in the repository
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()  # Need to run to log the workflow failure
    - name: Quick Metric
      env:
        QUICK_METRIC_API_KEY: ${{ secrets.QUICK_METRIC_API_KEY }}
      run: ./bin/post-metrics.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp /tmp/rare-test-events.plist .
        zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rare-test-events.plist
        path: rare-test-events.plist
